Error in Redis transaction frequency validation java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "org.springframework.data.redis.core.ValueOperations.increment(Object, long)" is null
RedisSystemException: Error in execution
Caused by: io.lettuce.core.RedisCommandExecutionException: ERR EXEC without MULTI